### ISSUE TITLE
Publish this as `nginx` in crates.io?

### ISSUE THREAD

**Issue by crlf0710** [nginxinc/ngx-rust#17]
It seems rather strange from a Rust user's view that a library has the name "rust" in it. Maybe just call this crate `nginx` or something.

**Comment by lfairy** [comment]
Yeah, this is mentioned in the [official API guidelines](https://rust-lang-nursery.github.io/api-guidelines/naming.html):

> Crate names should not use `-rs` or `-rust` as a suffix or prefix. Every crate is Rust! It serves no purpose to remind users of this constantly.

**Comment by repi** [comment]
Would indeed be nice to have it published as `nginx`, no need for a rust prefix/suffix in the crate name as that is exclusively in the Ruts ecosystem. Great to have it in the repository name here though

**Comment by ivanitskiy** [comment]
opened https://github.com/nginxinc/ngx-rust/pull/27

**Comment by dekobon** [comment]
A crate has been published. Closing issues.
