### ISSUE TITLE
Pin rustc version

### ISSUE THREAD

**Issue by Horki** [nginxinc/ngx-rust#21]
@sehz Please add a `rust-toolchain` file due to the inactivity of the project

**Comment by sehz** [comment]
Please reach out to NGINX about maintenance  of this project

**Comment by dekobon** [comment]
Hi @Horki , there have been a lot of changes to this project since you filed this bug in 2020. Do you still think pinning the rustc version is needed?

**Comment by Horki** [comment]
Hi @dekobon, I think this is not relevant anymore 👴
