### ISSUE TITLE
Make lint fails with errors

### ISSUE THREAD

**Issue by f5yacobucci** [nginxinc/ngx-rust#32]
Running `make lint` on the main branch generates errors.

1. git clone [ngx-rust project]
2. `make lint`

**Expected behavior**
Ideally, `make lint` should complete clean without warnings (`-D warnings`) or errors. But `make lint` (`cargo clippy`) must complete without errors.

**Your environment**
* Version of the repo - 4aa2e35259abace2fb87ed38ca3632e7c0b5c2e8
* Version of ngx-rust - 0.3.0-beta
* Version of Rust - 1.71.0-nightly
* Version of NGINX (and all dependencies if modified) - N/A
* OS and distribution - Ubuntu  22.04.2 LTS
* Details about containerization, virtualization, or physical environment - N/A

**Additional context**
Suggested tasks:
- Propose lint (clippy.toml) configuration for consistency
- Add git action to run lint appropriately (build / review)
- Run strict checks (`-D warnings`)
- Make main branch clean and free of error

**Comment by ivanitskiy** [comment]
done via https://github.com/nginxinc/ngx-rust/pull/46
