### ISSUE TITLE
publish as rust crate

### ISSUE THREAD

**Issue by sehz** [nginxinc/ngx-rust#5]
This is blocker for release. This need to be done in order for other crates to use this.

**Comment by sehyoc** [comment]
Moved to 0.2 release.

**Comment by ivanitskiy** [comment]
https://crates.io/crates/nginx-sys and https://crates.io/crates/ngx published today.

**Comment by yaa110** [comment]
@ivanitskiy I would like to hand over the ownership of `nginx` crate to you. If  you are OK, please send your username on crates.io, then I change the ownership of the crate.

**Comment by sehz** [comment]
Nicely done!  Great job @ivanitskiy

**Comment by ivanitskiy** [comment]
> @ivanitskiy I would like to hand over the ownership of `nginx` crate to you. If you are OK, please send your username on crates.io, then I will change the ownership of the crate.

Hi @yaa110, that would be great. Please use `ivanitskiy` for crates.io. Thanks for reaching out and providing this permission to take over.

**Comment by yaa110** [comment]
@ivanitskiy An invite has been sent to ivanitskiy. Please remove my account from the list of owners once you have accepted the invitation. Thanks

**Comment by ivanitskiy** [comment]
Done. I'm the only owner now. thank you!
